export const TabData = [{
        img: '../../icons/slider_img1.png',
        name: 'ROHAT Yog\ `i №2',
        title: "Mavjud",
        sale: "17,190, uzs",
        price: "16 000 uzs",
    },
    {
        img: '../../icons/slider_img2.png',
        name: 'Rohat Sirop',
        title: "Erkaklar kuchi",
        sale: "200,190, uzs",
        price: "150 000 uzs",
    },
    {
        img: '../../icons/slider_img3.png',
        name: 'Organic Bananas',
        title: "7pcs, Price",
        sale: "17,190, uzs",
        price: "16 000 uzs",
    },
    {
        img: '../../icons/slider_img4.png',
        name: 'ROHAT Yog\ `i №2',
        title: "Mavjud",
        sale: "17,190, uzs",
        price: "150 000 uzs",
    },
    {
        img: '../../icons/slider_img1.png',
        name: 'ROHAT Yog\ `i №2',
        title: "Mavjud",
        sale: "17,190, uzs",
        price: "16 000 uzs",
    },
    {
        img: '../../icons/slider_img2.png',
        name: 'Rohat Sirop',
        title: "Erkaklar kuchi",
        sale: "200,190, uzs",
        price: "150 000 uzs",
    },
    {
        img: '../../icons/slider_img3.png',
        name: 'Organic Bananas',
        title: "7pcs, Price",
        sale: "17,190, uzs",
        price: "16 000 uzs",
    },
    {
        img: '../../icons/slider_img4.png',
        name: 'ROHAT Yog\ `i №2',
        title: "Mavjud",
        sale: "17,190, uzs",
        price: "150 000 uzs",
    },
]