export const FAVORITEDOCTORDEL_TYPE_LOADING = `FAVORITEDOCTORDEL_TYPE_LOADING`;
export const FAVORITEDOCTORDEL_TYPE_SUCCESS = `FAVORITEDOCTORDEL_TYPE_SUCCESS`;
export const FAVORITEDOCTORDEL_TYPE_ERROR = `FAVORITEDOCTORDEL_TYPE_ERROR`;