
// GET
export const FAVORITEDOCTORS_TYPE_LOADING = `FAVORITEDOCTORS_TYPE_LOADING`;
export const FAVORITEDOCTORS_TYPE_SUCCESS = `FAVORITEDOCTORS_TYPE_SUCCESS`;
export const FAVORITEDOCTORS_TYPE_ERROR = `FAVORITEDOCTORS_TYPE_ERROR`;



// POST 

export const FAVORITDOCTOR_TYPE_LOADING = `FAVORITDOCTOR_TYPE_LOADING`;
export const FAVORITDOCTOR_TYPE_SUCCESS = `FAVORITDOCTOR_TYPE_SUCCESS`;
export const FAVORITDOCTOR_TYPE_ERROR = `FAVORITDOCTOR_TYPE_ERROR`;


// DELETE 
export const FAVORITEDOCTORDEL_TYPE_LOADING = `FAVORITEDOCTORDEL_TYPE_LOADING`;
export const FAVORITEDOCTORDEL_TYPE_SUCCESS = `FAVORITEDOCTORDEL_TYPE_SUCCESS`;
export const FAVORITEDOCTORDEL_TYPE_ERROR = `FAVORITEDOCTORDEL_TYPE_ERROR`;