export const SPECIALIST_DOCTORS_LOADING = "SPECIALIST_DOCTORS_LOADING"
export const SPECIALIST_DOCTORS_SUCCESS = "SPECIALIST_DOCTORS_SUCCESS"
export const SPECIALIST_DOCTORS_ERROR = "SPECIALIST_DOCTORS_ERROR"