
// Specialist Doctor GET
export const GET_TOPDOCTOR_LOADING = 'GET_TOPDOCTOR_LOADING';
export const GET_TOPDOCTOR_SUCCESS = 'GET_TOPDOCTOR_SUCCESS';
export const GET_TOPDOCTOR_ERROR = 'GET_TOPDOCTOR_ERROR';


// // Specialist Doctor GET By ID
export const GET_DOCTORBYID_LOADING = 'GET_DOCTORBYID_LOADING';
export const GET_DOCTORBYID_SUCCESS = 'GET_DOCTORBYID_LOADING';
export const GET_DOCTORBYID_ERROR = 'GET_DOCTORBYID_LOADING';