export const FAVORITEDOCTORS_TYPE_LOADING = `FAVORITEDOCTORS_TYPE_LOADING`;
export const FAVORITEDOCTORS_TYPE_SUCCESS = `FAVORITEDOCTORS_TYPE_SUCCESS`;
export const FAVORITEDOCTORS_TYPE_ERROR = `FAVORITEDOCTORS_TYPE_ERROR`;