// GET BY ID

export const GET_COMMENT_DOCTOR_LOADING = 'GET_COMMENT_DOCTOR_LOADING'
export const GET_COMMENT_DOCTOR_SUCCESS = 'GET_COMMENT_DOCTOR_SUCCESS'
export const GET_COMMENT_DOCTOR_ERROR = 'GET_COMMENT_DOCTOR_ERROR'


// POST BY ID
// export const GET_COMMENT_DOCTOR_LOADING = 'GET_COMMENT_DOCTOR_LOADING'
// export const GET_COMMENT_DOCTOR_SUCCESS = 'GET_COMMENT_DOCTOR_SUCCESS'
// export const GET_COMMENT_DOCTOR_ERROR = 'GET_COMMENT_DOCTOR_ERROR'