export const FAVORITDOCTOR_TYPE_LOADING = `FAVORITDOCTOR_TYPE_LOADING`;
export const FAVORITDOCTOR_TYPE_SUCCESS = `FAVORITDOCTOR_TYPE_SUCCESS`;
export const FAVORITDOCTOR_TYPE_ERROR = `FAVORITDOCTOR_TYPE_ERROR`;